services:
  client:
    image: nginx:alpine
    ports:
      - 8090:80
    volumes:
      - ./client:/usr/share/nginx/html

  sales-tax-rate:
    image: sales-tax-rate
    platform: wasi/wasm
    build:
      context: sales_tax_rate
    ports:
      - 8001:8001
    restart: unless-stopped
    runtime: io.containerd.wasmedge.v1

  order-total:
    image: order-total
    platform: wasi/wasm
    build:
      context: order_total
    ports:
      - 8002:8002
    environment:
      SALES_TAX_RATE_SERVICE: http://sales-tax-rate:8001/find_rate
      RUST_BACKTRACE: full
    restart: unless-stopped
    runtime: io.containerd.wasmedge.v1
